import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#0A192F' },
  header: {
    backgroundColor: '#0A192F',
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#1E293B',
  },
  headerTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  brandTitle: { fontSize: 22, fontWeight: '800', color: '#F8FAFC', letterSpacing: 0.5 },
  brandSubtitle: { fontSize: 11, color: '#94A3B8', marginTop: 2 },
  networkPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1E293B',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#334155',
  },
  networkStatusText: { fontSize: 10, fontWeight: '700', color: '#F59E0B', marginRight: 4 },
  dialectContainer: { flexDirection: 'row', alignItems: 'center', marginTop: 4 },
  dialectLabel: { fontSize: 11, color: '#94A3B8', marginRight: 8, fontWeight: '600' },
  dialectButton: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 14,
    backgroundColor: '#1E293B',
    marginRight: 6,
    borderWidth: 1,
    borderColor: '#334155',
  },
  dialectButtonActive: { backgroundColor: '#D97706', borderColor: '#F59E0B' },
  dialectButtonText: { fontSize: 11, color: '#CBD5E1', fontWeight: '600' },
  dialectButtonTextActive: { color: '#FFFFFF', fontWeight: '700' },
  contentArea: { flex: 1, backgroundColor: '#F1F5F9' },
  sectionContainer: { padding: 14 },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0F172A',
    marginBottom: 10,
    marginTop: 14,
  },
  // Module Card
  moduleCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 14,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 2,
    marginBottom: 14,
  },
  moduleMetaRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 6 },
  moduleTag: {
    backgroundColor: '#0D5C3A',
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '800',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    marginRight: 6,
  },
  moduleSubject: { fontSize: 11, color: '#475569', fontWeight: '600', marginRight: 8 },
  moduleSize: { fontSize: 10, color: '#64748B' },
  moduleTitle: { fontSize: 18, fontWeight: '800', color: '#0F172A', lineHeight: 24 },
  moduleSubtitle: { fontSize: 12, color: '#64748B', marginTop: 2, marginBottom: 12 },
  // Vector Canvas
  vectorCanvasContainer: {
    backgroundColor: '#F8FAFC',
    borderRadius: 8,
    padding: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 12,
  },
  canvasHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  canvasSlideTitle: { fontSize: 13, fontWeight: '700', color: '#0A192F', flex: 1 },
  canvasBadge: {
    fontSize: 9,
    fontWeight: '700',
    color: '#D97706',
    backgroundColor: '#FEF3C7',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  vectorCanvasBox: {
    backgroundColor: '#FFFFFF',
    borderRadius: 6,
    padding: 10,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    alignItems: 'center',
  },
  gridOverlay: {
    width: '100%',
    padding: 8,
    backgroundColor: '#F1F5F9',
    borderRadius: 6,
    alignItems: 'center',
    marginBottom: 6,
  },
  gridTitle: { fontSize: 10, color: '#64748B', fontWeight: '700', marginBottom: 6 },
  mockCitadel: {
    backgroundColor: '#DBEAFE',
    borderWidth: 1,
    borderColor: '#93C5FD',
    padding: 6,
    borderRadius: 4,
    width: '90%',
    alignItems: 'center',
    marginBottom: 4,
  },
  citadelText: { fontSize: 10, fontWeight: '700', color: '#1E40AF' },
  mockLowerTown: {
    backgroundColor: '#E0F2FE',
    borderWidth: 1,
    borderColor: '#BAE6FD',
    padding: 6,
    borderRadius: 4,
    width: '90%',
    alignItems: 'center',
  },
  lowerTownText: { fontSize: 10, fontWeight: '700', color: '#0369A1' },
  vectorCanvasDesc: { fontSize: 11, color: '#475569', textAlign: 'center', marginTop: 4 },
  bulletList: { marginTop: 8 },
  bulletItem: { fontSize: 12, color: '#1E293B', lineHeight: 18, marginBottom: 2 },
  transcriptBox: {
    backgroundColor: '#FEF3C7',
    borderRadius: 6,
    padding: 8,
    marginTop: 8,
    borderLeftWidth: 3,
    borderLeftColor: '#D97706',
  },
  transcriptLabel: { fontSize: 10, fontWeight: '700', color: '#92400E', marginBottom: 2 },
  transcriptText: { fontSize: 12, color: '#78350F', fontStyle: 'italic', lineHeight: 17 },
  // Audio Controls
  audioController: { marginTop: 4 },
  audioTimeRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 8 },
  audioTimeText: { fontSize: 11, color: '#64748B', fontWeight: '600' },
  audioTrack: {
    flex: 1,
    height: 6,
    backgroundColor: '#E2E8F0',
    borderRadius: 3,
    marginHorizontal: 8,
    overflow: 'hidden',
  },
  audioProgressFill: { height: '100%', backgroundColor: '#0D5C3A' },
  audioButtonsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  slideNavButton: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: '#F1F5F9',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#CBD5E1',
  },
  slideNavButtonText: { fontSize: 11, fontWeight: '600', color: '#334155' },
  playButton: { backgroundColor: '#0D5C3A', paddingHorizontal: 18, paddingVertical: 8, borderRadius: 20 },
  playButtonText: { color: '#FFFFFF', fontSize: 13, fontWeight: '700' },
  // Quiz Card
  quizCard: { backgroundColor: '#FFFFFF', borderRadius: 12, padding: 14, elevation: 2 },
  quizHeader: {
    fontSize: 14,
    fontWeight: '800',
    color: '#0A192F',
    marginBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
    paddingBottom: 6,
  },
  quizItem: { marginBottom: 14 },
  quizQuestion: { fontSize: 13, fontWeight: '700', color: '#1E293B', marginBottom: 6, lineHeight: 18 },
  quizOption: {
    padding: 8,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 5,
    backgroundColor: '#F8FAFC',
  },
  quizOptionSelected: { backgroundColor: '#DBEAFE', borderColor: '#3B82F6' },
  quizOptionText: { fontSize: 12, color: '#334155' },
  quizOptionTextSelected: { color: '#1E40AF', fontWeight: '700' },
  explanationBox: {
    backgroundColor: '#ECFDF5',
    padding: 8,
    borderRadius: 6,
    marginTop: 4,
    borderWidth: 1,
    borderColor: '#A7F3D0',
  },
  explanationText: { fontSize: 11, color: '#065F46', lineHeight: 16 },
  submitQuizButton: {
    backgroundColor: '#0A192F',
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 6,
  },
  submitQuizButtonText: { color: '#FFFFFF', fontSize: 12, fontWeight: '700' },
  // Scholarship Section
  card: { backgroundColor: '#FFFFFF', borderRadius: 12, padding: 14, elevation: 2, marginBottom: 10 },
  cardHeading: { fontSize: 15, fontWeight: '800', color: '#0A192F' },
  cardSubheading: { fontSize: 11, color: '#64748B', marginTop: 2, marginBottom: 12, lineHeight: 15 },
  profileRow: { marginBottom: 10 },
  profileLabel: { fontSize: 12, fontWeight: '600', color: '#334155', marginBottom: 4 },
  pillGroup: { flexDirection: 'row' },
  smallPill: {
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 14,
    backgroundColor: '#F1F5F9',
    marginRight: 6,
    borderWidth: 1,
    borderColor: '#CBD5E1',
  },
  smallPillActive: { backgroundColor: '#0A192F', borderColor: '#0A192F' },
  smallPillText: { fontSize: 11, color: '#475569', fontWeight: '600' },
  smallPillTextActive: { color: '#FFFFFF', fontWeight: '700' },
  switchRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
  },
  scholarshipCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    padding: 12,
    marginBottom: 10,
    borderLeftWidth: 4,
    elevation: 1,
  },
  borderEligible: { borderLeftColor: '#10B981' },
  borderIneligible: { borderLeftColor: '#94A3B8', opacity: 0.85 },
  scholarshipTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 6,
  },
  scholarshipTitle: { fontSize: 14, fontWeight: '800', color: '#0F172A' },
  scholarshipDept: { fontSize: 10, color: '#64748B', marginTop: 1 },
  statusBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 12 },
  badgeEligible: { backgroundColor: '#D1FAE5' },
  badgeIneligible: { backgroundColor: '#F1F5F9' },
  statusBadgeText: { fontSize: 10, fontWeight: '700', color: '#065F46' },
  benefitText: { fontSize: 12, color: '#1E293B', fontWeight: '600', marginTop: 4 },
  estimatedAmount: { fontSize: 11, color: '#D97706', fontWeight: '700', marginTop: 2 },
  rejectionBox: { backgroundColor: '#FEF2F2', padding: 6, borderRadius: 6, marginTop: 6 },
  rejectionText: { fontSize: 10, color: '#B91C1C', lineHeight: 14 },
  toggleDocsButton: { marginTop: 8, paddingVertical: 4 },
  toggleDocsText: { fontSize: 11, color: '#2563EB', fontWeight: '600' },
  docsList: {
    backgroundColor: '#F8FAFC',
    borderRadius: 6,
    padding: 8,
    marginTop: 6,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  docsHeader: { fontSize: 10, fontWeight: '700', color: '#334155', marginBottom: 4 },
  docItem: { fontSize: 11, color: '#475569', lineHeight: 16 },
  portalRef: { fontSize: 10, color: '#64748B', marginTop: 4, fontStyle: 'italic' },
  // Doubt Section
  textInput: {
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 8,
    padding: 10,
    fontSize: 13,
    color: '#0F172A',
    textAlignVertical: 'top',
    marginBottom: 10,
  },
  doubtActionRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  voiceRecordButton: {
    backgroundColor: '#F1F5F9',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  voiceRecordingActive: { backgroundColor: '#FEE2E2', borderColor: '#EF4444' },
  voiceRecordText: { fontSize: 11, fontWeight: '700', color: '#334155' },
  sendDoubtButton: { backgroundColor: '#0D5C3A', paddingHorizontal: 16, paddingVertical: 8, borderRadius: 8 },
  sendDoubtText: { color: '#FFFFFF', fontSize: 12, fontWeight: '700' },
  doubtCard: { backgroundColor: '#FFFFFF', borderRadius: 10, padding: 12, marginBottom: 10, elevation: 1 },
  doubtHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  doubtTimestamp: { fontSize: 10, color: '#64748B' },
  doubtStatusBadge: { paddingHorizontal: 8, paddingVertical: 2, borderRadius: 10 },
  doubtResolvedBadge: { backgroundColor: '#D1FAE5' },
  doubtPendingBadge: { backgroundColor: '#FEF3C7' },
  doubtStatusText: { fontSize: 9, fontWeight: '700', color: '#0F172A' },
  doubtQuestion: { fontSize: 13, fontWeight: '700', color: '#0F172A', lineHeight: 18 },
  doubtAnswerBox: {
    backgroundColor: '#F0FDF4',
    padding: 8,
    borderRadius: 6,
    marginTop: 8,
    borderLeftWidth: 3,
    borderLeftColor: '#10B981',
  },
  doubtAnswerLabel: { fontSize: 10, fontWeight: '700', color: '#065F46', marginBottom: 2 },
  doubtAnswerContent: { fontSize: 12, color: '#047857', lineHeight: 17 },
  doubtCitation: { fontSize: 9, color: '#065F46', marginTop: 4, fontStyle: 'italic' },
  doubtPendingNote: { fontSize: 11, color: '#D97706', marginTop: 6, fontStyle: 'italic' },
  // Career Section
  careerBanner: { backgroundColor: '#0A192F', borderRadius: 10, padding: 12, marginBottom: 12 },
  careerBannerTitle: { fontSize: 14, fontWeight: '800', color: '#F8FAFC' },
  careerBannerSubtitle: { fontSize: 11, color: '#94A3B8', marginTop: 2, lineHeight: 15 },
  careerCard: { backgroundColor: '#FFFFFF', borderRadius: 10, padding: 14, marginBottom: 12, elevation: 2 },
  careerTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  badgeUrgency: { backgroundColor: '#FEF3C7', paddingHorizontal: 8, paddingVertical: 2, borderRadius: 4 },
  badgeUrgencyText: { fontSize: 10, fontWeight: '800', color: '#D97706' },
  careerIncome: { fontSize: 13, fontWeight: '800', color: '#0D5C3A' },
  careerTitle: { fontSize: 15, fontWeight: '800', color: '#0F172A' },
  careerCategory: { fontSize: 11, color: '#64748B', marginTop: 1, marginBottom: 6 },
  careerOverview: { fontSize: 12, color: '#334155', lineHeight: 17, marginBottom: 8 },
  careerMetaBox: { backgroundColor: '#F8FAFC', padding: 8, borderRadius: 6, marginBottom: 8 },
  careerMetaText: { fontSize: 11, color: '#475569', marginBottom: 2 },
  roadmapBox: { borderTopWidth: 1, borderTopColor: '#F1F5F9', paddingTop: 8 },
  roadmapHeading: { fontSize: 11, fontWeight: '700', color: '#0A192F', marginBottom: 4 },
  roadmapStep: { fontSize: 11, color: '#334155', lineHeight: 16, marginBottom: 2 },
  // Bottom Navigation
  bottomNav: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 60,
    backgroundColor: '#0A192F',
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: '#1E293B',
    elevation: 8,
  },
  navItem: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  navItemActive: { borderTopWidth: 2, borderTopColor: '#D97706' },
  navIcon: { fontSize: 18, opacity: 0.6 },
  navIconActive: { opacity: 1, transform: [{ scale: 1.1 }] },
  navLabel: { fontSize: 10, color: '#94A3B8', marginTop: 2, fontWeight: '600' },
  navLabelActive: { color: '#F59E0B', fontWeight: '800' },
  // Media Mode Toggle
  mediaModeSelector: {
    flexDirection: 'row',
    backgroundColor: '#F1F5F9',
    borderRadius: 8,
    padding: 3,
    marginBottom: 12,
  },
  mediaModeBtn: { flex: 1, paddingVertical: 7, alignItems: 'center', borderRadius: 6 },
  mediaModeBtnActive: {
    backgroundColor: '#0A192F',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  mediaModeBtnText: { fontSize: 11, fontWeight: '700', color: '#475569' },
  mediaModeBtnTextActive: { color: '#FFFFFF' },
  // Video Player
  videoPlayerContainer: {
    backgroundColor: '#000000',
    borderRadius: 10,
    overflow: 'hidden',
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#334155',
  },
  videoCanvas: { backgroundColor: '#0F172A', minHeight: 260, padding: 10, justifyContent: 'space-between' },
  videoOverlayTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  videoWatermark: { fontSize: 10, color: '#94A3B8', fontWeight: '700', letterSpacing: 0.5 },
  videoQualityBadge: {
    backgroundColor: 'rgba(217, 119, 6, 0.2)',
    borderWidth: 1,
    borderColor: '#D97706',
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  videoQualityBadgeText: { fontSize: 9, color: '#F59E0B', fontWeight: '800' },
  videoVisualCenter: { alignItems: 'center', justifyContent: 'center', paddingVertical: 14 },
  facultyAvatarPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(30, 41, 59, 0.9)',
    borderRadius: 16,
    paddingHorizontal: 10,
    paddingVertical: 4,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#475569',
  },
  facultyAvatarIcon: { fontSize: 14, marginRight: 6 },
  facultyAvatarLabel: { fontSize: 11, fontWeight: '700', color: '#F8FAFC' },
  videoScreenBoard: {
    width: '94%',
    backgroundColor: '#1E293B',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#3B82F6',
    padding: 12,
    alignItems: 'center',
  },
  boardTopicTitle: { fontSize: 12, fontWeight: '800', color: '#38BDF8', marginBottom: 4 },
  boardVisualArt: { fontSize: 13, fontWeight: '700', color: '#F59E0B', marginVertical: 6 },
  boardSubText: { fontSize: 10, color: '#94A3B8' },
  videoSubtitleOverlay: {
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    borderRadius: 6,
    padding: 8,
    marginVertical: 8,
    borderLeftWidth: 3,
    borderLeftColor: '#F59E0B',
  },
  subtitleDialectTag: { fontSize: 9, fontWeight: '800', color: '#F59E0B', marginBottom: 2 },
  subtitleText: { fontSize: 12, color: '#FFFFFF', lineHeight: 17 },
  videoControlsOverlay: { backgroundColor: 'rgba(15, 23, 42, 0.95)', borderRadius: 6, padding: 8 },
  videoTimelineRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 8 },
  videoTimeText: { fontSize: 10, color: '#94A3B8', fontWeight: '600' },
  videoProgressBar: {
    flex: 1,
    height: 4,
    backgroundColor: '#334155',
    borderRadius: 2,
    marginHorizontal: 8,
    overflow: 'hidden',
  },
  videoProgressFill: { height: '100%', backgroundColor: '#EF4444' },
  videoBottomControlsRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  videoPlayBtn: { backgroundColor: '#0D5C3A', paddingHorizontal: 12, paddingVertical: 5, borderRadius: 14 },
  videoPlayBtnText: { color: '#FFFFFF', fontSize: 11, fontWeight: '800' },
  qualitySelectorRow: { flexDirection: 'row' },
  qualityPill: { paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4, backgroundColor: '#334155', marginRight: 4 },
  qualityPillActive: { backgroundColor: '#D97706' },
  qualityPillText: { fontSize: 9, color: '#94A3B8', fontWeight: '700' },
  qualityPillTextActive: { color: '#FFFFFF' },
  speedSelectorRow: { flexDirection: 'row' },
  speedPill: { paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4, backgroundColor: '#334155', marginRight: 4 },
  speedPillActive: { backgroundColor: '#2563EB' },
  speedPillText: { fontSize: 9, color: '#94A3B8', fontWeight: '700' },
  speedPillTextActive: { color: '#FFFFFF' },
  videoNoticeBox: { backgroundColor: '#0F172A', padding: 8, borderTopWidth: 1, borderTopColor: '#1E293B' },
  videoNoticeText: { fontSize: 10, color: '#38BDF8', lineHeight: 14 },
});

export default styles;

